# Generated by Django 3.1 on 2020-08-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='text',
            new_name='checktext',
        ),
        migrations.AlterField(
            model_name='predict',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
